version: "3.9"
services:
  myelectricaldata_import:
    image: m4dm4rtig4n/myelectricaldata:0.8.13-beta2
    environment:
      TZ: Europe/Paris
    ports:
      - '5000:5000'
    links:
      - influxdb
      - mosquitto
    volumes:
      - ./../data/cache:/data
      
  influxdb:
    image: influxdb:2.4
    ports:
      - '8086:8086'
    volumes:
      - ./../data/influxdb:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://influxdb:8086"]
      interval: 25s
      timeout: 3s
      start_period: 30s
    environment:
      TZ: Europe/Paris
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: myelectricaldata
      DOCKER_INFLUXDB_INIT_PASSWORD: myelectricaldata
      DOCKER_INFLUXDB_INIT_ORG: myelectricaldata
      DOCKER_INFLUXDB_INIT_BUCKET: myelectricaldata
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: myelectricaldata

  mosquitto:
    image: eclipse-mosquitto:2.0.12
    environment:
      TZ: Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./../data/mosquitto:/data
      - ./../mosquitto:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001

  mqtt_explorer:
    image: smeagolworms4/mqtt-explorer
    environment:
      TZ: Europe/Paris
    links:
      - mosquitto
    volumes:
      - ./../data/:/mqtt-explorer/config
    ports:
      - 4000:4000

volumes:
  mydata:
