name: Push latest

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ steps.vars.outputs.version }} =~ .*\-.*$ ]]; then
              echo ::set-output name=dev::true
          else
            echo "::set-output name=dev::false"
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.check-tag.outputs.match != 'false'
        with:
          context: .
          platforms: linux/arm/v6
          push: true
          tags: |
            m4dm4rtig4n/enedisgateway2mqtt:latest
            m4dm4rtig4n/enedisgateway2mqtt:${{ steps.vars.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.check-tag.outputs.match != 'true'
        with:
          context: .
          platforms: linux/arm/v6
          push: true
          tags: |
            m4dm4rtig4n/enedisgateway2mqtt:${{ steps.vars.outputs.version }}