on:
  issues:
    types: [opened] 
permissions:
  contents: write
  issues: write    
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        if: "!contains(github.event.issue.labels.*.name, 'bug help enhancement')"
        uses: YiiGuxing/close-issue@v2.1.0
        with:
          comment: "Merci de respecter le template initial !"
