name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The tag RC version to release."
        required: true

jobs:

  informations:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Generate release version
        id: informations
        run: |
          echo "version=$(${{ github.event.inputs.version }} |awk -F '-' '{print $1}')" >> "$GITHUB_OUTPUT"

    outputs:
      version: ${{ steps.informations.outputs.version }}

  Begin:
    needs: [informations]
    name: Begin
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Discord notification building state
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '**MyElectricalData** : Version **${{ needs.informations.outputs.version }}** is in building state...'

  #################################################################################################################
  # BUILD & PUSH IMAGE
  Build-And-Push-Image:
    needs: [informations, Begin]
    name: Build & Push
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #################################################################################################################
      # SETUP DOCKER
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #################################################################################################################
      # VERSION
      - name: Build and push ${{ needs.informations.outputs.version }} / latest-dev
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v6, linux/arm/v7
          context: .
          push: true
          tags: |
            m4dm4rtig4n/enedisgateway2mqtt:${{ needs.informations.outputs.version }}
            m4dm4rtig4n/enedisgateway2mqtt:latest-dev            
            m4dm4rtig4n/myelectricaldata:${{ needs.informations.outputs.version }}            
            m4dm4rtig4n/myelectricaldata:latest-dev
            m4dm4rtig4n/enedisgateway2mqtt:latest
            m4dm4rtig4n/myelectricaldata:latest


  Finish:
    needs: [informations, Build-And-Push-Image]
    name: Finish
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '**MyElectricalData** : New version available **${{ needs.informations.outputs.version }}**'