name: "Build/Push Release"

on:
  workflow_dispatch:

env:
  IMAGE_REPO: m4dm4rtig4n
  IMAGE_NAME: myelectricaldata

jobs:

  informations:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${IMAGE_REPO}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate release version
        id: informations
        run: |
          version=$(cat src/__version__.py |grep VERSION| awk '{print $3}' | tr -d '"')
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          
          if [ $(docker manifest inspect ${IMAGE_REPO}/${IMAGE_NAME}:${version}  > /dev/null ; echo $?) -eq 0 ]; then
            echo "Image already build => SKIP BUILDING"          
            echo "build=false" >> "$GITHUB_OUTPUT"
          else
            echo "build=true" >> "$GITHUB_OUTPUT"    
          fi

    outputs:
      version: ${{ steps.informations.outputs.version }}
      build: ${{ steps.informations.outputs.build }}

  Discord-Begin:
    needs: [informations]
    if: ${{ needs.informations.outputs.build  == 'true' }}
    uses: MyElectricalData/.github/.github/workflows/discord.yaml@main
    with:
      MESSAGE: '**MyElectricalData** : Version **${{ needs.informations.outputs.version }}** is in building state...'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  Build-And-Push-Image:
    needs: [informations, Discord-Begin]
    if: ${{ needs.informations.outputs.build  == 'true' }}
    uses: MyElectricalData/.github/.github/workflows/dockerhub-build-push.yaml@main
    with:
      IMAGE_REPO: ${IMAGE_REPO}
      IMAGE_NAME: ${IMAGE_NAME}
      PUSH: true
      TAG: ${{ needs.informations.outputs.version }}
      PLATFORM: "linux/amd64, linux/arm64, linux/arm/v6, linux/arm/v7"
      LATEST: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  Discord-Finish:
    needs: [informations, Build-And-Push-Image]
    if: ${{ needs.informations.outputs.build  == 'true' }}
    uses: MyElectricalData/.github/.github/workflows/discord.yaml@main
    with:
      MESSAGE: '**MyElectricalData** : New version available **${{ needs.informations.outputs.version }}**'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
