name: "Build/Push Image to Docker Hub"

on:
  workflow_run:
    workflows: ["semantic_release"]
    types:
      - completed

env: 
  IMAGE_REPO: m4dm4rtig4n
  IMAGE_NAME: myelectricaldata

jobs:

  informations:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: informations
        run: |
          version=v$(cat src/__version__.py |grep VERSION| awk '{print $3}' | tr -d '"')
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          release_type=$(cat src/__version__.py |grep VERSION| awk '{print $3}' | tr -d '"'| grep rc)
          if [ "$release_type" == "" ]; then
            # RELEASE
            echo "release_type=release" >> "$GITHUB_OUTPUT"
          else
            # PRERELEASE
            echo "release_type=prerelease" >> "$GITHUB_OUTPUT"
          fi

          if [ $(docker manifest inspect ${IMAGE_REPO}/${IMAGE_NAME}:${version}) == "" ]; then
            echo "build=true" >> "$GITHUB_OUTPUT"
          else
            echo "build=false" >> "$GITHUB_OUTPUT"         

    outputs:
      version: ${{ steps.informations.outputs.version }}
      release_type: ${{ steps.informations.outputs.release_type }}
      build: ${{ steps.informations.outputs.build }}

  Discord-Begin:
    uses: MyElectricalData/.github/actions/discord@main
    with:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MESSAGE: '**MyElectricalData** : Version **${{ needs.informations.outputs.version }}** is in building state...'

  Build-And-Push-Image:
    needs: [informations, Begin]
    uses: MyElectricalData/.github/actions/dockerhub-build-push@main
    with:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_REPO: ${IMAGE_REPO}
      IMAGE_NAME: ${IMAGE_NAME}
      PUSH: true
      TAG: ${{ needs.informations.outputs.version }}
      PLATFORM: "linux/amd64, linux/arm64, linux/arm/v6, linux/arm/v7"
      LATEST: false

  Discord-Finish:
    uses: MyElectricalData/.github/actions/discord@main
    with:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MESSAGE: '**MyElectricalData** : New version available **${{ needs.informations.outputs.version }}**'
