name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The tag RC version to release."
        required: true

env:
  IMAGE_REPO: m4dm4rtig4n
  IMAGE_NAME: myelectricaldata

jobs:

  informations:
    runs-on: [ ubuntu-latest ]
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate release version
        id: informations
        run: |
          version=$(echo "${{ github.event.inputs.version }} |awk -F '-' '{print $1}')"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          
          if [ $(docker manifest inspect ${IMAGE_REPO}/${IMAGE_NAME}:${version}) == "" ]; then
            echo "build=true" >> "$GITHUB_OUTPUT"
          else
            echo "build=false" >> "$GITHUB_OUTPUT"    

    outputs:
      version: ${{ steps.informations.outputs.version }}
      build: ${{ steps.informations.outputs.build }}

  Discord-Begin:
    needs: [informations]
    if: ${{ needs.informations.outputs.build  == true }}
    uses: MyElectricalData/.github/actions/discord@main
    with:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MESSAGE: '**MyElectricalData** : Version **${{ needs.informations.outputs.version }}** is in building state...'

  Build-And-Push-Image:
    needs: [informations, Discord-Begin]
    uses: MyElectricalData/.github/actions/dockerhub-build-push@main
    with:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_REPO: ${IMAGE_REPO}
      IMAGE_NAME: ${IMAGE_NAME}
      PUSH: true
      TAG: ${{ needs.informations.outputs.version }}
      PLATFORM: "linux/amd64, linux/arm64, linux/arm/v6, linux/arm/v7"
      LATEST: true

  Discord-Finish:
    needs: [Build-And-Push-Image]
    uses: MyElectricalData/.github/actions/discord@main
    with:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MESSAGE: '**MyElectricalData** : New version available **${{ needs.informations.outputs.version }}**'