name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The tag RC version to release."
        required: true

jobs:
  release:
    name: Deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ref/tags/${{ inputs.version }}