name: "[PRODUCTION] Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:

  Semantic-Release:
    uses: MyElectricalData/.github/.github/workflows/python_semantic_release_input.yaml@main
    with:
      PRE_RELEASE: false
