name: "[STAGING] Pre-Release"

on:
  push:
    branches:
      - main

jobs:

  Semantic-Pre-Release:
    uses: MyElectricalData/.github/.github/workflows/python_semantic_release_input.yaml@main
    with:
      PRE_RELEASE: true

  Trig-Generate-Pre-Release:
    needs: ["Semantic-Pre-Release"]
    runs-on: ubuntu-latest
    steps:      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: generate_prerelease