name: "[STAGING] Pre-Release"

on:
  push:
    branches:
      - coucou

jobs:

  Semantic-Pre-Release:
    uses: MyElectricalData/.github/.github/workflows/python_semantic_release_input.yaml@main
    with:
      PRE_RELEASE: true
